ecommerce/urls.py
from django.contrib import admin
from .views import *
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^$|^/$|home/', home, name='homepage'),
    path('admin/', admin.site.urls),
    path("login/", include('login.urls')),
    path("shop/", include('shop.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *


app_name = 'login'

urlpatterns = [
    path('registration/', UserCreateView.as_view(), name="registration"),
    path('login/', UserLogin.as_view(), name="login"),
    path('logout/', UserLogout.as_view(), name="logout"),
    path('userinfo/', UserDetails.as_view(), name='userdetails'),
    path('dashboard/<int:pk>/', DashboardSeller.as_view(), name='dashboard'),
    path('yourproduct/', ProductSeller.as_view(), name='yourproduct'),
    path('yourorder/', OrderList.as_view(), name='yourorder')
]

shop/urls.py
from django.urls import path
from .views import *


app_name = 'shop'

urlpatterns = [
    path('items/', ProductsListView.as_view(), name="items"),
    path('<slug:slug>/details/', ProductDetails.as_view(), name="itemdetails"),
    path('<slug:slug>/buyitem', BuyProduct.as_view(), name='buyitem'),
    path('<slug:slug>/addorder/', add_order, name="addorder"),
    path('search/', search, name="search"),
    path('size_filter/', size_filter, name="size_filter"),
    path('price_filter/', price_filter, name="price_filter"),
    #path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/list', category_filter, name='category_filter'),
    path('create_product/', ProductSeller_Create.as_view(), name='create'),
    path('<slug:slug>/delete', ProductSeller_Delete.as_view(), name='delete'),
    path('<slug:slug>/update', ProductSeller_Update.as_view(), name='update'),
    path('<slug:slug>/review', review, name='review_product'),
    path('<int:pk>/review_seller', review_seller, name='review_seller'),
    path('seller_details/<int:pk>/', SellerDetails.as_view(), name='sellerdetails'),

    
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields

class CustomUserForm(UserCreationForm):
    is_seller = fields.BooleanField(label='I am a seller', required=False)

    class Meta:
        model = User
        fields = ['username','email','password1', 'password2']

login/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import User, Group
from login.forms import CustomUserForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView, LogoutView
from shop.models import *
from django.urls import reverse_lazy
# Create your views here.

class UserCreateView(CreateView):
    form_class = CustomUserForm
    template_name = 'login/user_creation.html'
    success_url = reverse_lazy("homepage")

    def form_valid(self,form):
        valid = super().form_valid(form)
        user = form.save(commit=False)
        user.save()

        if form.cleaned_data['is_seller']:
            user_group = Group.objects.get(name="seller")
            user.groups.add(user_group)
        
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password1'],
        )
        login(self.request, user)

        return valid

class UserLogin(LoginView):
    template_name = 'login/login.html'
    next_page = reverse_lazy('homepage')

class UserLogout(LogoutView):
    template_name = 'login/logout.html'
    next_page = reverse_lazy('homepage')

class UserDetails(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'login/info_user.html'
   
    def get_object(self):
        return self.request.user
    def get_context_data(self, **kwargs):
        tot=0
        context = super().get_context_data(**kwargs)
        num_orders = Order.objects.filter(customer_id = self.request.user)
        context['num_orders'] = len(num_orders)
        for order in num_orders:
            tot += order.product.price
        context['sum_orders'] = tot
        
        return context

class ProductSeller(GroupRequiredMixin, ListView):

    raise_exception = True
    group_required = ["seller"]
    model = Product
    template_name = 'login/product_seller.html'

    def get_queryset(self):
        return Product.objects.all().filter(seller=self.request.user)

class DashboardSeller(GroupRequiredMixin, DetailView):

    raise_exception = True
    group_required = ["seller"]
    model = User
    template_name = 'login/dashboard_seller.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_review'] = None
        num_reviews = 0
        tot = 0
        total_score = 0


        # REVENUE
        orders =Order.objects.filter(product_id__in=Product.objects.filter(seller=self.get_object().id).values_list('id',flat=True)) 
        context["total_sold_products"] = len(orders)
        for order in orders:
            tot += order.product.price
            context["total_sold_revenue"] = tot

        context["orders"] = orders

        # RATING
        total_seller_reviews = ReviewSeller.objects.filter(seller_id=self.get_object().id)
        context['total_seller_reviews'] = len(total_seller_reviews)

        for review in ReviewSeller.objects.filter(seller_id=self.get_object().id):
            num_reviews += 1
            total_score += review.stars
        try:
            context['average_rating'] = round(float(total_score/num_reviews),2)
        except:
            context['average_rating'] = 0
        
        # REVIEW
        try:
            if self.request.user.is_authenticated:
                seller_id = self.get_object().id
                user_id = User.objects.get(username=self.request.user).id
                review = ReviewSeller.objects.all().filter(seller_id =seller_id)

                
                if review:
                    context['my_review'] = review
        except:
            pass

        return context


class OrderList(LoginRequiredMixin,ListView):
    model = Order
    template_name = 'login/yourorder.html'
    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user)

login/templates/login/dashboard_seller.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
   
    <p class="is-size-2 title">Dashboard di {{ object }}</p><br>
    <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Rating medio</p>
            <p class="title">{{average_rating}}/5</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Numero valutazioni</p>
            <p class="title">{{total_seller_reviews}}</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Incasso</p>
            <p class="title">{{total_sold_revenue}}€</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Prodotti venduti</p>
            <p class="title">{{total_sold_products}}</p>
          </div>
        </div>
      </nav>

    <br>
    
    {% if request.user.is_authenticated %}
    
    
    <h5><strong>Ordini dei clienti</strong></h5>

                <div class="list-group">
                    {% for order in orders %}

                    <div class="list-group-item">
                      <b>{{ order.product.title }}</b>
                            <div class="tags are-medium is-pulled-right ">
                              <span class="tag is-info">{{ order.customer }}</span>
                          </div>
                          
                    </div>
                    {% endfor %}
                </div>

                <br>

                <br>
                <hr>
                <h5><strong>Recensioni dei clienti</strong></h5>
                <br>
                {% for review in my_review %}
                <article class="message">
                  <div class="message-header "  style="background-color:hsl(188, 68%, 25%)">
                      <p>{{review.reviewer}}</p>
                      <p class="is-right">{{review.created_at|date:"d M Y"}}</p>
                  </div>
                  <div class="message-body">
                          <p>Valutazione {{ review.stars }}/5<span style="color:#ff9900">&#9733;</span></p>
                          
                  </div>
              </article>
                <br>
                {% endfor %}
               
        
            
            
    {% endif %}

  
{% endblock content %}

login/templates/login/info_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dettagli {{ object }}{% endblock title %}

{% block content %}
    <section class="is-large">
    <h1 class="title">Dettagli di {{ object }}</h1>
    <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Numero ordini acquistati</p>
            <p class="title">{{num_orders}}</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Totale speso</p>
            <p class="title">{{sum_orders}}€</p>
          </div>
        </div>

      </nav>
    <div>
        Username: <b>{{ user}}</b><br>
        Indirizzo e-mail: <b>{{ user.email }}</b>
        
    </div>

    <br>

</section>
{% endblock content %}

login/templates/login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form | crispy}}
      <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

login/templates/login/logout.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock  %}

{% block content %}
<h1>goodbye</h1>
{% endblock  %}

login/templates/login/product_seller.html
{% extends 'base.html'%}
{% load static %}

{% block content %} 
<h1 class="mb-4">Elenco prodotti in vendita</h1>
{% if not object_list %}
    No sales yet
{% endif %}
<div class="list-group">
    {% for product in object_list %}
        <div class="list-group-item">
            <b><a href="{% url 'shop:itemdetails' product.slug %}" class="has-text-dark  is-active" >{{ product.title }}</a></b> 
            <a href="{% url 'shop:delete' product.slug %}" class="float-right btn btn-danger is-pulled-right ml-2">Remove</a> 
            <a href="{% url 'shop:update' product.slug %}" class=" float-right btn btn-primary is-pulled-right ml-2">Modifica</a>
            
        </div>
    {% endfor %}
</div>
<div>
     <a href="{% url 'shop:create' %}"> 
        <button class="btn btn-primary is-pulled-center mt-3">Aggiungi Vendita</button>
    </a>
</div>

{% endblock %}

login/templates/login/user_creation.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Registration{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form | crispy}}

    <input type="submit" class="btn btn-success" value="Sign Up">
</form>
{% endblock %}

login/templates/login/yourorder.html
{% extends 'base.html'%}
{% load static %}

{% block content %} 

<h1 class="is-size-2 title">I tuoi ordini</h1>
{% if not object_list %}
    No sales yet
{% endif %}
<div class="list-group">
    {% for product in object_list %}
        <div class="list-group-item">
            <b><a href="{% url 'shop:itemdetails' product.product.slug %}" class="has-text-dark is-active" >{{ product.product.title }}</a></b> 
            <div class="tags are-medium is-pulled-right ">
                <span class="tag is-info">{{ product.product.price }}€</span>
            </div>
            
        </div>
    {% endfor %}
</div>
<br><br><br>
{% endblock %}