ecommerce/urls.py
from django.contrib import admin
from .views import *
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^$|^/$|home/', home, name='homepage'),
    path('admin/', admin.site.urls),
    path("login/", include('login.urls')),
    path("shop/", include('shop.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *


app_name = 'login'

urlpatterns = [
    path('registration/', UserCreateView.as_view(), name="registration"),
    path('login/', UserLogin.as_view(), name="login"),
    path('logout/', UserLogout.as_view(), name="logout"),
    path('userinfo/', UserDetails.as_view(), name='userdetails'),
    path('dashboard/<int:pk>/', DashboardSeller.as_view(), name='dashboard'),
    path('yourproduct/', ProductSeller.as_view(), name='yourproduct'),
    path('yourorder/', OrderList.as_view(), name='yourorder')
]

shop/urls.py
from django.urls import path
from .views import *


app_name = 'shop'

urlpatterns = [
    path('items/', ProductsListView.as_view(), name="items"),
    path('<slug:slug>/details/', ProductDetails.as_view(), name="itemdetails"),
    path('<slug:slug>/buyitem', BuyProduct.as_view(), name='buyitem'),
    path('<slug:slug>/addorder/', add_order, name="addorder"),
    path('search/', search, name="search"),
    path('size_filter/', size_filter, name="size_filter"),
    path('price_filter/', price_filter, name="price_filter"),
    #path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/list', category_filter, name='category_filter'),
    path('create_product/', ProductSeller_Create.as_view(), name='create'),
    path('<slug:slug>/delete', ProductSeller_Delete.as_view(), name='delete'),
    path('<slug:slug>/update', ProductSeller_Update.as_view(), name='update'),
    path('<slug:slug>/review', review, name='review_product'),
    path('<int:pk>/review_seller', review_seller, name='review_seller'),
    path('seller_details/<int:pk>/', SellerDetails.as_view(), name='sellerdetails'),

    
]

templates/base.html
{% load static %}
{% load static group_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>  Ecommerce  {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  
  <body>
    <nav class="navbar is-transparent" style="background-color:hsl(188, 68%, 25%)"role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'homepage' %}">
          <img src="{% static 'img/logo1.png' %}" width="40" height="28">
        </a>
        
    
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
    
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          
          <a class="navbar-item has-text-white is-active" href="{% url 'homepage' %}">Home</a>
          <a class="navbar-item has-text-white is-active" href="{% url 'shop:items' %}" >Shop</a>
        </div>
        
    
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              {% if request.user.is_authenticated %}
              <div class="navbar-item has-dropdown is-hoverable">
                <b><a class="navbar-link has-text-white">{{user.username}}</a></b>
                
                <div class="navbar-dropdown is-right">
                  {% if request.user|is_group:'seller' %}
                  <a class="dropdown-item" href="{% url 'login:yourproduct' %}">I tuoi prodotti</a>
                  <a class="dropdown-item" href="{% url 'login:dashboard' user.id %}">Dashboard</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'login:yourorder' %}">I tuoi ordini</a>
                  <a class="dropdown-item" href="{% url 'login:userdetails' %}">Informazioni account</a>
                  {% else %}
                  <a class="dropdown-item" href="{% url 'login:yourorder' %}">I tuoi ordini</a>
                  <a class="dropdown-item" href="{% url 'login:userdetails' %}">Informazioni account</a>
                  {% endif %}
                  
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'login:logout' %}">Logout</a>
                </div>
                </div>
              {% else %}
              <a class="button is-light" href="{% url 'login:registration' %}"><strong>Sign up</strong></a>
              <a class="button is-light" href="{% url 'login:login' %}">Log in</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <section class="section is-medium">
      <div class="row">
        <div class="col-2">{% block left_section %} {% endblock left_section %}</div>
        <div class="col-8">
          
            {% block content %}
            
           
          
		      {%include 'search_form.html'%}
          {%include 'carousel.html'%}
          {%include 'reccomandation.html'%}
          
                {% endblock %}
          
        </div>
        <div class="col-2">{% block right_section %}{% endblock right_section %}</div>
      </div>
  
		
		</section>
    


    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
      
    
      
    
    
    {%block footer%} {%include 'footer.html'%}{%endblock%}
  </body>

templates/breadcrumb.html
<section class="is-large">
  <nav class="breadcrumb is-centered" aria-label="breadcrumbs">
      <ul>
        <li><a href="{% url 'homepage' %}">Home</a></li>
        <li><a href="{% url 'shop:items' %}">Shop</a></li>
        <li class="is-active"><a href="#" aria-current="page">{{object.title}}</a></li>
      </ul>
    </nav>
</section>

templates/carousel.html
<section class="section is-medium">
    
    <h3 class="is-size-3 has-text-centered">Scopri le nostre categorie</h3>
    <div id="carousel-demo" class="carousel">
    
          
        {% for category in categories %}
        <div class="item">
           
                <div class="card">
                <a href="{% url 'shop:category_filter' category.slug %}">
                <img src="{{ category.image.url }}" class="img-fluid" ></a>
                
                    <div class="card-body">
                    <h6 class="card-title is-size-5 has-text-centered">{{ category.title }}</h6>
                </div>
                
            </div>
            <br>
        </div>
        {%endfor%}
    </div>
    <br><br><br><br>
    
</section>

templates/filters.html
<nav class="panel">
    <p class="panel-heading has-text-white" style="background-color:hsl(188, 68%, 25%)">
      Prezzo
    </p>
    <form method="GET" action="{% url 'shop:price_filter' %}">
        <input class="input is-transparent" name="min_price" type="number" min="0" placeholder="0">
        <input class="input is-transparent" name="max_price" type="number" placeholder="Max">
        <div class="panel-block">
            <button type="submit" class="button is-black is-outlined is-fullwidth">
              Filtra
            </button>
          </div>
    </form>
    
</nav>
<article class="panel ">
    <p class="panel-heading has-text-white is-center" style="background-color:hsl(188, 68%, 25%)">Categorie</p>
    {% for category in categories %}
    <a class="panel-block is-active" href="{% url 'shop:category_filter' category.slug%}">
      <span class="panel-icon">
        <i class="fas fa-book" aria-hidden="true"></i>
      </span>
      {{category.title}}
    </a>
    {%endfor%}
  </article>

  
<nav class="panel ">
  <p class="panel-heading has-text-white" style="background-color:hsl(188, 68%, 25%)">
    Taglia
  </p>
  <div class="container">
  <form method="GET" action="{% url 'shop:size_filter' %}">
    
    <label class="checkbox">
      <input type="checkbox" name="size" value="XL">
      XL
    </label><br>
    <label class="checkbox">
      <input type="checkbox" name="size" value="L">
      L
    </label><br>
    <label class="checkbox">
      <input type="checkbox" name="size" value="M">
      M
    </label><br>
    <label class="checkbox mr-4">
      <input type="checkbox" name="size" value="S" >
      S
    </label><br>
  </div>
    
      <div class="panel-block">
          <button type="submit" class="button is-black is-outlined is-fullwidth">
            Filtra
          </button>
        </div> 
  </form>
  
</nav>

templates/footer.html
<footer class="footer" style="background-color:hsl(188, 68%, 25%)"">
    <div class="content has-text-centered">
      <p class="has-text-white">
        <strong class="has-text-white">Project</strong> by <a href="https://gitlab.com/274292">Riccardo Prini</a>. The source code is 
        <a href="https://gitlab.com/274292/techweb2122">here</a>. A.A 2022/2023</a>.
      </p>
    </div>
  </footer>

templates/reccomandation.html
{% load static group_tags %}


    
    

<section class="section container ">
{% if request.user.is_authenticated %}

    {% if request.user|is_group:'seller' %}
    <h1 class="is-size-3" >Le tue vendite.</h1>

    <div id="carousel-demo" class="carousel">
    
          
        {% for order in selled_product %}
        <div class="item">
            <div class="box-element product">
                <a href="{% url 'shop:itemdetails' order.product.slug %}">
                <img src="{{ order.product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
                <div class="card-body">
                    <h6 class="card-title">{{ order.product.title }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted"> {{ order.date|date:"d F Y" }} </h6>
                    <h6 class="card-subtitle mb-2 text-muted"> {{ order.customer }} </h6>
                </div>
            </div>
            <br>
        </div>
        
        {% endfor %}
    </div>
    {% else %}
    <h1 class="is-size-3" >Consigliati per te.</h1>
    <br> 
    {%if product_reccomandation|length != 0 %}
    <h1 class="is-size-5" >In base alle tue preferenze:</h1>
    <div id="carousel-demo" class="carousel">
    
          
        {% for product in product_reccomandation %}
        <div class="item">
            <div class="box-element product">
                <a href="{% url 'shop:itemdetails' product.slug %}">
        <img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
                <div class="card-body">
                    <h6 class="card-title">{{ product.title }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
                </div>
            </div>
            <br>
        </div>
        
        {% endfor %}
    </div>

    <br><br><br>
    {%endif%}
    {%if last_prod|length != 0 %}
    <h1 class="is-size-5" >In base a quello che hai vistato:</h1>
    <div id="carousel-demo" class="carousel">
    
          
        {% for product in last_prod %}
        <div class="item">
            <div class="box-element product">
                <a href="{% url 'shop:itemdetails' product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
                <div class="card-body">
                    <h6 class="card-title">{{ product.title }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
                </div>
            </div>
            <br>
        </div>
        
        {% endfor %}
    </div>
    </div>
    {%endif%}
    {%endif%}
</section>
  {%endif%}

templates/search_form.html
{% load static %}
<section class="section container">
  <div class="content is-normal">
    <main role="main" class="container">
      
      <h1 class="has-text-centered  is-size-1" >Trova i prodotti adatti a te.</h6>
     
      <form method="GET" action="{% url 'shop:search' %}">
        <div class="field has-addons ">
          <div class="control is-expanded">
            <input class="input" type="text" name="title_contains" placeholder="Cerca..">
          </div>
          <div class="control ">
             <button class="button has-text-white" style="background-color:hsl(188, 68%, 25%)">Search</button>
           </div>

        </div>
      
        <p class="has-text-centered is-size-6">Non sai cosa cercare? {% for prod in random_product%}<a href="{% url 'shop:itemdetails' prod.slug %}" class="has-text-dark is-active"  ><b>Lasciati ispirare</b></a>{%endfor%}</p>
            <p class="has-text-centered is-size-7">Le nostre categorie: {%for cat in categories%}<b><a href="{% url 'shop:category_filter' cat.slug%}" class="has-text-dark is-active">{{cat.title}}</a></b> {%endfor%}</p>
      </div> 

      
      </div>
      
    </div>
  </form>
  
    </main>
  </section>