ecommerce/urls.py
from django.contrib import admin
from .views import *
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^$|^/$|home/', home, name='homepage'),
    path('admin/', admin.site.urls),
    path("login/", include('login.urls')),
    path("shop/", include('shop.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from .views import *


app_name = 'login'

urlpatterns = [
    path('registration/', UserCreateView.as_view(), name="registration"),
    path('login/', UserLogin.as_view(), name="login"),
    path('logout/', UserLogout.as_view(), name="logout"),
    path('userinfo/', UserDetails.as_view(), name='userdetails'),
    path('dashboard/<int:pk>/', DashboardSeller.as_view(), name='dashboard'),
    path('yourproduct/', ProductSeller.as_view(), name='yourproduct'),
    path('yourorder/', OrderList.as_view(), name='yourorder')
]

shop/urls.py
from django.urls import path
from .views import *


app_name = 'shop'

urlpatterns = [
    path('items/', ProductsListView.as_view(), name="items"),
    path('<slug:slug>/details/', ProductDetails.as_view(), name="itemdetails"),
    path('<slug:slug>/buyitem', BuyProduct.as_view(), name='buyitem'),
    path('<slug:slug>/addorder/', add_order, name="addorder"),
    path('search/', search, name="search"),
    path('size_filter/', size_filter, name="size_filter"),
    path('price_filter/', price_filter, name="price_filter"),
    #path('categories/', CategoryListView.as_view(), name='categories'),
    path('category/<slug:slug>/list', category_filter, name='category_filter'),
    path('create_product/', ProductSeller_Create.as_view(), name='create'),
    path('<slug:slug>/delete', ProductSeller_Delete.as_view(), name='delete'),
    path('<slug:slug>/update', ProductSeller_Update.as_view(), name='update'),
    path('<slug:slug>/review', review, name='review_product'),
    path('<int:pk>/review_seller', review_seller, name='review_seller'),
    path('seller_details/<int:pk>/', SellerDetails.as_view(), name='sellerdetails'),

    
]

shop/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django_extensions.db.fields import AutoSlugField
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
SIZE_CHOICES = (
        ('XL', 'XL'),
        ('L', 'L'),
        ('M', 'M'),
        ('S', 'S'),
    )

class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = AutoSlugField(max_length=255, populate_from='title')
    image = models.ImageField(null=True)

    class Meta:
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    seller = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    size =  models.CharField(max_length=2, choices=SIZE_CHOICES, default="XL")
    slug = AutoSlugField(max_length=255, populate_from='title')
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField()

    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        return self.title

        
    def score(self):
        reviews = ReviewProduct.objects.filter(product=self)
        num = len(reviews)
        tot = 0
        if num == 0:
             return 0
        
        for review in reviews:
            tot += review.stars
        avg=float(tot/num)
        result = round(avg, 1)
        return result
            
    def get_reviews_num(self):
        reviews = ReviewProduct.objects.filter(product=self)
        return len(reviews)

    def get_reviews(self):
        reviews = ReviewProduct.objects.filter(product=self)
        review_details = []

        for review in reviews:
            review_details.append((review))
        
        return review_details
        
    def get_average_score(self):
        total_score = 0
        reviews = ReviewProduct.objects.filter(product=self)
        num_reviews = len(reviews)

        if num_reviews != 0:
            for review in reviews:
                total_score += review.stars
        
            return float(total_score/num_reviews)
        
        return 0



class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product}'


class Review(models.Model):
    
    
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    stars = models.IntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1)
        ]
    )

    class Meta:
        abstract = True

class ReviewProduct(Review):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.CharField(max_length=512, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product}'


class ReviewSeller(Review):
    seller = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="seller")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.seller}' 

shop/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['title', 'description', 'price','size', 'image', 'category']


class ProductReviewForm(forms.Form):
    CHOICE_LIST = [(i,i) for i in range(1,6)]
    review_value = forms.ChoiceField(
        label="Punteggio ",
        required=True,
        choices=CHOICE_LIST
    )
    review_text = forms.CharField()


class SellerReviewForm(forms.Form):
    CHOICE_LIST = [(i,i) for i in range(1,6)]
    review_value = forms.ChoiceField(
        label="Punteggio ",
        required=True,
        choices=CHOICE_LIST
    )

shop/views.py
from django.shortcuts import render,redirect
from django.utils import timezone
from django.views.generic.list import ListView
from braces.views import GroupRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView,CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy
from .forms import *
from .models import *
from django.db.models import Q

# Create your views here.

class ProductSeller_Create(GroupRequiredMixin, CreateView):
    raise_exception = True
    group_required = ["seller"]
    form_class = ProductForm
    model = Product
    template_name = 'shop/create_product.html'
    success_url = reverse_lazy('login:yourproduct')

    def form_valid(self, form):
        form.instance.seller_id = self.request.user.id
        return super().form_valid(form)

class ProductSeller_Delete(GroupRequiredMixin, DeleteView):
    raise_exception = True
    group_required = ["seller"]
    model = Product
    template_name = 'shop/delete_product.html'
    success_url = reverse_lazy('login:yourproduct')

class ProductSeller_Update(GroupRequiredMixin, UpdateView):
    raise_exception = True
    group_required = ["seller"]
    form_class = ProductForm
    model = Product
    template_name = 'shop/update_product.html'
    success_url = reverse_lazy('login:yourproduct')



class ProductsListView(ListView):
    model = Product
    template_name = 'shop/item_list.html'

    def get_context_data(self, **kwargs):
        # Categorie
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BuyProduct(LoginRequiredMixin, DetailView):
    success_url = reverse_lazy('shop:itemdetails')
    template_name = 'shop/buy_product.html'
    model = Product

def add_order(request,slug):
    order = Order(
            customer = User.objects.get(id=request.user.id),
            product = Product.objects.get(slug=slug),
            date = timezone.now(),
        )
    order.save()
    return redirect('shop:itemdetails', slug)

class ProductDetails(DetailView):
    model = Product
    template_name = 'shop/item_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Categoria
        rs_category = Product.objects.filter(category_id=self.get_object().category_id).exclude(id=self.get_object().id)
        context['rs_category'] = rs_category
        # Prezzo
        price = self.get_object().price
        bias = 30
        rs_price = Product.objects.filter(price__gte=price-bias,price__lte=price+bias).exclude(id=self.get_object().id).exclude(category_id=self.get_object().category_id)

        context['rs_price'] = rs_price

        context['already_reviewed'] = False
        context['my_review'] = None
        try:
            if self.request.user.is_authenticated:
                product = self.get_object().id
                user_id = User.objects.get(username=self.request.user).id
                review = ReviewProduct.objects.get(product_id=product, reviewer_id=user_id)

                if review:
                    context['my_review'] = review
                    context['already_reviewed'] = True
        except:
            pass

        return context

class SellerDetails(DetailView):
    model = User
    template_name = 'shop/seller_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['self_review'] = False
        context['already_reviewed'] = False
        context['my_review'] = None
        
        num_reviews = 0
        total_score = 0
        context['seller_products'] = Product.objects.filter(seller_id = self.get_object().id)
        total_seller_reviews = ReviewSeller.objects.filter(seller_id=self.get_object().id)
        context['total_seller_reviews'] = len(total_seller_reviews)

        for review in ReviewSeller.objects.filter(seller_id=self.get_object().id):
            num_reviews += 1
            total_score += review.stars
        try:
            context['average_rating'] = round(float(total_score/num_reviews),2)
        except:
            context['average_rating'] = 0

        try:
            if self.request.user.is_authenticated:
                seller_id = self.get_object().id
                #user_id = User.objects.get(username=self.request.user).id
                review = ReviewSeller.objects.all().filter(seller_id =seller_id )

                
                if review:
                    context['my_review'] = review
                    context['already_reviewed'] = True
        except:
            pass

        try:
            if self.request.user.is_authenticated:
                seller_id = self.get_object().id
                reviewer_id = User.objects.get(username=self.request.user).id
                if seller_id == reviewer_id:
                    context['self_review'] = True
        except:
            pass

        return context 


def review(request, slug):
    template = 'shop/reviews.html'
    ctx = {
        "form": ProductReviewForm(),
        "seller": None,
        "product": slug
    }

    if request.method == "POST":
        form = ProductReviewForm(request.POST)

        if form.is_valid():
            review = ReviewProduct()
            review.stars = form.cleaned_data.get('review_value')
            review.text = form.cleaned_data.get('review_text')
            review.product = Product.objects.get(slug=slug)
            review.reviewer = User.objects.get(username=request.user.username)
            
            review.save()
            return redirect("shop:itemdetails", slug)

    return render(request, template_name=template, context=ctx)




#  Reviewer del venditore
def review_seller(request, pk):
    template = 'shop/reviews.html'
    ctx = {
        'form': SellerReviewForm(),
        'vendor': pk
    }

    if request.method == "POST":
        form = SellerReviewForm(request.POST)

        if form.is_valid():
            review = ReviewSeller()
            review.stars = form.cleaned_data.get('review_value')
            review.reviewer = User.objects.get(username=request.user.username)
            review.seller = User.objects.get(id=pk)
            review.save()
            return redirect("shop:sellerdetails", pk)

    return render(request, template_name=template, context=ctx)


def is_valid_queryparam(param):
    return param != '' and param is not None



# Searching
def search(request):
    products = Product.objects.all()
    query = (str)(request.GET.get('title_contains'))
    if is_valid_queryparam(query):
        products = products.filter(Q(title__icontains=query) | Q(category__title__icontains=query) | Q(description__icontains=query))    
    return render(request, 'shop/search.html', {'products':products, 'query':'','categories':Category.objects.all()})

def price_filter(request):
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')

    if min_price == '' or max_price == '':
        return redirect('shop:items')
    
    min_price= (int)(min_price)
    max_price= (int)(max_price)
     
    if min_price > max_price:
        return redirect('shop:items')

    products = Product.objects.filter(price__gte=min_price, price__lte=max_price)
    category = Category.objects.all()
    ctx = {
        'min_price':min_price,
        'max_price':max_price,
        'products':products,
        'categories':category,
    }

    return render(request, 'shop/price_filter.html', ctx)

def category_filter(request,slug):
    category = Category.objects.all()
    products = Product.objects.filter(category__slug=category.get(slug=slug).slug)
    ctx = {
        'categories':category,
        'products':products
    }
    return render(request, 'shop/category_filter.html', ctx)
    
def size_filter(request):
    category = Category.objects.all()
    size_list = request.GET.getlist('size')
    print(size_list)
    products = Product.objects.filter(size__in=size_list)
    print(products)
    ctx = {
        'categories':category,
        'products':products
    }
    return render(request, 'shop/size_filter.html',ctx)

shop/templates/shop/buy_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Buy product{% endblock title %}

{% block content %}
    
<p class="is-size-3">Confermi l'acquisto del seguente prodotto?</p>
    <div class="card">
        <div class="card-image">
            <figure class="image is-4by3">
            <img src="{{ product.image.url }}" alt="Placeholder image">
            </figure>
        </div>
        <div class="card-content">
        <h6>{{ object.title }}</h6>
        <h6>€ {{object.price}}</h6>
        <h6>Category: {{ object.category }}</h6>
        <p>{{ object.description }}</p>
        <form class="float-right"method="post" action="{% url 'shop:addorder' product.slug %}">
            {% csrf_token %}
            {{ form | crispy}}
            <br>
            <a href="{% url 'shop:itemdetails' product.slug %}" class="button is-secondary">Annulla</a>
            <input type="submit" value="Conferma" class="button is-success">
        </form>
    </div>
    </div>
    
   
{% endblock content %}

shop/templates/shop/categories.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Categorie{% endblock %}

{% block content %}

<h2>Categorie</h2>
    <br>
    <div class="row">
        {% for category in object_list %}
        <div class="col-lg-3">
            <div>
                <a class="btn btn-outline-info" href="{% url 'shop:category_filter' category.slug %}">{{ category.title }}</a>
            </div>
            <br>
        </div>
        {% endfor %}
    </div>

{% endblock content %}

shop/templates/shop/category_filter.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Filter{% endblock %}
{% block left_section %}{%include 'filters.html'%}{% endblock %}
{% block content %}


<div class="text-center">
    {% if not products %}
    No products found
    {% endif %}
</div>
<br>
<div class="row">
    {% for product in products %}
    <div class="col-lg-3">
        <div class="box-element product">
            <a href={% url 'shop:itemdetails' product.slug %}><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
            <div class="card-body">
                <h6 class="card-title">{{ product.title }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

shop/templates/shop/create_product.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Add a product{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Add product" class="btn btn-primary">
</form>
{% endblock %}

shop/templates/shop/delete_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Delete product{% endblock title %}

{% block content %}
    <br>
    <p class="is-size-3">Vuoi rimuovere il seguente prodotto dalle tue vendite?</p>
    <div class="card border-danger">
        <br>
        <div class="card-image">
            <figure class="image is-3by4">
            <img src="{{ product.image.url }}" alt="Placeholder image">
            </figure>
        </div>
        <div class="card-content">
        <h6>{{ object.title }}</h6>
        <h6>€ {{object.price}}</h6>
        <h6>Categoria: {{ object.category }}</h6>
        <p>{{ object.description }}</p>
            
        <form class="float-right" method="post">
            {% csrf_token %}
            {{ form | crispy}}
            <br>
            <a href="{% url 'login:yourproduct' %}" class="button is-secondary">Annulla</a>
            <input type="submit" value="Elimina" class="button is-danger">
        </form>
    </div>

    </div>
    
   
{% endblock content %}

shop/templates/shop/item_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}- {{ object.title }} - details{% endblock title %}


{% block content %}
<section class="is-medium">
    {%include 'breadcrumb.html'%}
   
    <h1 class="title is-size-2">
       {{ object.title }}
    </h1>
    <br>
    <div class="container">
        <div class="row">
            
            <div>
                <img height="400px" src="{{ object.image.url }}" style="object-fit: cover"> 
            </div>
            <div class="m-lg-3">
                Venduto da: <a href="{% url 'shop:sellerdetails' object.seller.pk%}">{{ object.seller }}</a>
                <br>
                <br>
                {% if object.get_average_score == 0 %}
                <p class="is-size-6">Nessuna recensione</p>
                {% else %}
                <h4>{{object.score}}/5<span style="color:#ff9900">&#9733;</span> ({{object.get_reviews_num}})</h4>
                {% endif %}
                
                <br><strong>Categoria</strong>: {{object.category}}        
                <br>
                <h5 class="is-size-3 title">€ {{ object.price }}</h5>
                <br>
                <a href="{% url 'shop:buyitem' object.slug%}" class="button is-info">Acquista</a>
            </div>
        </div>
        
        <br>
        <br>
        <h5><strong>Descrizione prodotto:</strong></h5>
        <p> {{ object.description }} </p> 
        <br>
        
        
        
        <br><br><br>

       
        <h4><strong>Confronta con prodotti simili</strong> </h4>
        {% if rs_category|length != 0 %}
        <h5><strong>Categoria simile</strong> </h5>
        <div class="row">
            
           
            {% for product in rs_category %}
            <div class="col-lg-3">
                <div class="box-element product">
                    <a href="{% url 'shop:itemdetails' product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
                    <div class="card-body">
                        <h6 class="card-title">{{ product.title }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted"><a href="{% url 'shop:sellerdetails' product.seller.pk %}">{{product.seller}}</a></h6>
                        <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
                    </div>
                </div>
                <br>
            </div>
            
            {% endfor %}
            {%endif%}
            </div>
            {% if rs_price|length != 0 %}
        <h5><strong>Prezzo simile</strong> </h5>
        <div id="carousel-demo" class="carousel">
        
            
            
            {% for product in rs_price %}
            <div class="item">
                <div class="box-element product">
                    <a href="{% url 'shop:itemdetails' product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
                    <div class="card-body">
                        <h6 class="card-title">{{ product.title }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted"><a href="{% url 'shop:sellerdetails' product.seller.pk %}">{{product.seller}}</a></h6>
                        <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
                    </div>
                </div>
                <br>
            </div>
            
            {% endfor %}
            {%endif%}
        </div>
        
    
          <br>
        
        <br>
        
             

       
        <h3 class="title" style="color:hsl(188, 68%, 25%)">Recensioni</h3>
        {% if not request.user.is_authenticated %}
            <a href="{% url 'login:login' %}" class="btn btn-outline-dark">Accedi per visualizzare le recensioni</a>
        {% else %}
            {% if object.get_reviews_num == 0 %}
            <h6>Nessuna recensione</h6> 
            <br>
            {% endif %}
            {% if already_reviewed %}
                <h5><strong>La tua recensione</strong></h5>
                <article class="message">
                    <div class="message-header "  style="background-color:hsl(188, 68%, 25%)">
                        <p>{{my_review.reviewer}}</p>
                        <p class="is-right">{{my_review.date|date:"d M Y"}}</p>
                    </div>
                    <div class="message-body">
                            <p>{{my_review.stars }}/5<span style="color:#ff9900">&#9733;</span></p>
                            <p>{{ my_review.text }}</p>
                    </div>
                </article>
                <br>
                <hr>
            {% else %}
                <a href="{% url 'shop:review_product' object.slug %}">
                    <div>
                        <button class="button is-info">Lascia una recensione!</button>
                    </div>
                </a>
            {% endif %}
            <br>
            {% if object.get_average_score != 0 %}
            <h5><strong>Recensioni clienti</strong></h5>
            {% endif %}
           
            <br>    
          <section>
              
            {% for review in object.get_reviews %}
            <article class="message">
                <div class="message-header "  style="background-color:hsl(188, 68%, 25%)">
                    <p>{{review.reviewer}}</p>
                    <p class="is-right">{{review.date|date:"d M Y"}}</p>
                </div>
                <div class="message-body">
                        <p>{{ review.stars }}/5<span style="color:#ff9900">&#9733;</span></p>
                        <p>{{ review.text }}</p>
                </div>
            </article>
                <br><br>
            {% endfor %}
        </section>
            
        {% endif %}
        
        
    </section>
{% endblock content %}

shop/templates/shop/item_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Products{% endblock %}
{% block first_row %}
{% endblock first_row %}

{% block left_section %}{%include 'filters.html'%}{% endblock %}

{% block content %}

    
    <div class="row">
        {% for product in object_list %}
        <div class="col-lg-3">
            <div class="box-element product">
                <a href="{% url 'shop:itemdetails' product.slug %}">
                    <img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
                <div class="card-body">
                    <h6 class="card-title">{{ product.title }}</h6>
                    <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
                </div>
            </div>
            <br>
        </div>
        
        {% endfor %}
    </div>
    
{% endblock %}

shop/templates/shop/price_filter.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Filter{% endblock %}
{% block left_section %}{%include 'filters.html'%}{% endblock %}
{% block content %}


<div class="text-center">
    {% if not products %}
    No products found
    {% endif %}
</div>
<br>
<div class="row">
    {% for product in products %}
    <div class="col-lg-3">
        <div class="box-element product">
            <a href={% url 'shop:itemdetails' product.slug %}><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
            <div class="card-body">
                <h6 class="card-title">{{ product.title }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

shop/templates/shop/reviews.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block title %}Review{% endblock %}

{% block content %}
    {% if vendor is not None %}
        <form method="POST" action="#"> {% csrf_token %}
    {% else %}
        <form method="POST" action="{% url 'shop:review_product' product %}"> {% csrf_token %}
    {% endif %}
        {{ form | crispy }}
        <input type="submit" value="Confirm" class="btn btn-outline-success">
    </form>
{% endblock content %}

shop/templates/shop/search.html
{% extends 'base.html' %}

{% block title %}Cerca{% endblock %}

{% block left_section %}{%include 'filters.html'%}{% endblock %}
{% block content %}
<div class="text-center">
    {% if not products %}
    No products found
    {% endif %}
</div>
<br>
<br>
<div class="row">
    {% for product in products %}
    <div class="col-lg-3">
        <div class="box-element product">
            <a href={% url 'shop:itemdetails' product.slug %}><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
            <div class="card-body">
                <h6 class="card-title">{{ product.title }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock  %}

shop/templates/shop/seller_details.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    
    <h1 class="is-size-2 title">
        Dettagli di {{ object }}
    </h1>
    <br>
    <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Rating medio</p>
            <p class="title">{{average_rating}}/5</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Numero valutazioni</p>
            <p class="title">{{total_seller_reviews}}</p>
          </div>
        </div>
      </nav>
    <div>
        Indirizzo e-mail: <b>{{ object.email }}</b>
    </div>
   

    <br><br>
    
    {% if request.user.is_authenticated %}
        {% if not already_reviewed and not self_review %}
            <a href="{% url 'shop:review_seller' object.pk%}">
                <div>
                    <button class="button is-info">Lascia una recensione!</button>
                </div>
            </a>
        
        {% elif already_reviewed %}
                <h5><strong>Recensioni clienti</strong></h5>
                <br>
                {% for review in my_review %}
                <article class="message">
                    <div class="message-header "  style="background-color:hsl(188, 68%, 25%)">
                        <p>{{review.reviewer}}</p>
                        <p class="is-right">{{review.created_at|date:"d M Y"}}</p>
                    </div>
                    <div class="message-body">
                            <p>Valutazione {{ review.stars }}/5<span style="color:#ff9900">&#9733;</span></p>
                            
                    </div>
                </article>
                <br>
                {% endfor %}
                <hr>
        {% endif %}
            
        <br><br>
        

        <p class="is-size-3 title">Prodotti venditore</p>
        <div id="carousel-demo" class="carousel">
    
          
            {% for product in seller_products %}
            <div class="item">
                <div class="box-element product">
                    <a href="{% url 'shop:itemdetails' product.slug %}"><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
                    <div class="card-body">
                        <h6 class="card-title">{{ product.title }}</h6>
                        <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
                    </div>
                </div>
                <br>
            </div>
            
            {% endfor %}
        </div>    
    {% endif %}

{% endblock content %}

shop/templates/shop/size_filter.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Filter{% endblock %}
{% block left_section %}{%include 'filters.html'%}{% endblock %}
{% block content %}


<div class="text-center">
    {% if not products %}
    No products found
    {% endif %}
</div>
<br>
<div class="row">
    {% for product in products %}
    <div class="col-lg-3">
        <div class="box-element product">
            <a href={% url 'shop:itemdetails' product.slug %}><img src="{{ product.image.url }}" class="card-img-top" style="height:12vw; object-fit: scale-down;"></a>
            <div class="card-body">
                <h6 class="card-title">{{ product.title }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">€ {{ product.price }} </h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

shop/templates/shop/update_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}- Update product{% endblock title %}

{% block content %}
    <br>

    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <br>
        <a href="{% url 'login:yourproduct' %}" class="button is-secondary">Annulla</a>
        <input type="submit" value="Modifica" class="button is-info">
    </form>
{% endblock content %}